export const GET_PROPERTIES_REQUEST = 'GET_PROPERTIES_REQUEST';
export const GET_PROPERTIES_SUCCESS = 'GET_PROPERTIES_SUCCESS';
export const GET_PROPERTIES_FAILURE = 'GET_PROPERTIES_FAILURE';

export const CHANGE_ACTIVE_PORTAL = 'CHANGE_ACTIVE_PORTAL';
export const SEE_MORE_PROPERTIES = 'SEE_MORE_PROPERTIES';